#pragma once

#include "ACPI/ACPI.h"
#include "AssemblyFunction.h"
#include "Console.h"
#include "Error.h"
#include "Graphics.h"
#include "Heap.h"
#include "Interrupt.h"
#include "Memory.h"
#include "MemoryManager.h"
#include "MultiProcessor.h"
#include "PCI.h"
#include "Segmentation.h"
#include "Task.h"
#include "Timer.h"
#include "Type.h"